/**
 * Centralized Branding Configuration
 *
 * Single source of truth for brand identity across all outputs:
 * - Compliance Matrix (XLSX)
 * - Gap Analysis PDF
 * - Submission Readiness Report PDF
 *
 * Addresses GitHub Issue #7: Consistent branding across outputs
 */

/**
 * Brand Colors (Attlee AI)
 */
export const BRAND_COLORS = {
  // Primary palette
  primary: '#1B2A4A',      // Navy blue (headers, key elements)
  accent: '#00B4A0',       // Teal (highlights, CTAs)

  // Status colors
  success: '#10B981',      // Green (compliant, passed)
  warning: '#F59E0B',      // Amber (review required, in progress)
  danger: '#DC2626',       // Red (blockers, critical)
  info: '#3B82F6',         // Blue (informational)

  // Neutral palette
  textPrimary: '#0F172A',  // Dark slate (body text)
  textSecondary: '#64748B', // Slate (secondary text)
  border: '#E2E8F0',       // Light gray (borders)
  background: '#F8FAFC',   // Off-white (backgrounds)
  white: '#FFFFFF',

  // Excel-specific colors (ARGB format for ExcelJS)
  excel: {
    primary: 'FF1B2A4A',
    accent: 'FF00B4A0',
    success: 'FFD4EDDA',
    warning: 'FFFFF3CD',
    danger: 'FFF8D7DA',
    headerBg: 'FF1E40AF',
    headerText: 'FFFFFFFF',
    rowAlt: 'FFF8FAFC',
    border: 'FFE2E8F0',

    // Resolution status colors
    statusOpen: 'FFFFD966',      // Yellow
    statusInProgress: 'FFFFC000', // Amber
    statusResolved: 'FFD4EDDA',   // Green
    statusNA: 'FFE2E8F0'          // Gray
  }
} as const;

/**
 * Typography
 */
export const BRAND_TYPOGRAPHY = {
  // Font families
  fontFamily: {
    primary: 'Calibri, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    heading: 'Calibri, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    mono: '"Courier New", Courier, monospace'
  },

  // Font sizes (for PDFs)
  fontSize: {
    coverTitle: '32pt',
    h1: '18pt',
    h2: '14pt',
    h3: '12pt',
    h4: '11pt',
    body: '10.5pt',
    small: '9pt',
    tiny: '8pt'
  },

  // Font weights
  fontWeight: {
    normal: 400,
    medium: 500,
    semibold: 600,
    bold: 700
  }
} as const;

/**
 * Logo Configuration
 */
export const BRAND_LOGO = {
  // Logo text (when image not available)
  text: 'Attlee AI',
  tagline: 'AI-Powered BSR Compliance',

  // Logo dimensions
  height: 40,  // pixels
  position: 'top-left' as const,

  // Logo URL (for web/email)
  url: 'https://www.attlee.ai',

  // Footer text
  footer: '🤖 Generated by Attlee AI | AI-Powered BSR Compliance',
  footerUrl: 'www.attlee.ai'
} as const;

/**
 * Page Layout
 */
export const BRAND_LAYOUT = {
  // PDF margins (in CSS units)
  pdf: {
    margin: {
      top: '40px',
      right: '60px',
      bottom: '40px',
      left: '60px'
    },
    maxWidth: '900px',

    // Page numbering format
    pageNumberFormat: (current: number, total: number) => `Page ${current} of ${total}`
  },

  // Excel layout
  excel: {
    columnWidths: {
      id: 8,
      requirement: 50,
      category: 15,
      status: 12,
      priority: 10,
      whatsWrong: 40,
      whyItMatters: 40,
      request: 50,
      owner: 20,
      evidenceDoc: 25,
      page: 8,
      evidenceQuote: 60,
      evidenceQuality: 12,
      notes: 50,
      resolutionStatus: 15,
      resolvedBy: 20,
      resolvedDate: 12
    },
    headerRow: 14,
    dataStartRow: 15,
    summaryRows: {
      start: 1,
      end: 13
    }
  }
} as const;

/**
 * Version Information
 */
export const BRAND_VERSION = {
  product: 'Attlee AI Compliance Platform',
  version: '1.0',
  versionDate: '2024',
  buildNumber: process.env.BUILD_NUMBER || 'dev'
} as const;

/**
 * Project Metadata Template
 * Addresses GitHub Issue #8
 */
export interface ProjectMetadata {
  projectName: string;
  siteAddress?: string;
  clientName?: string;
  applicationReference?: string;
  reviewDate: string;
  gatewayStage: 'Gateway 2' | 'Gateway 3' | 'Pre-submission';
  documentVersion?: string;
  buildingType?: string;
  heightMeters?: number;
  storeys?: number;
}

/**
 * Default metadata when not available
 */
export const DEFAULT_PROJECT_METADATA: ProjectMetadata = {
  projectName: 'BSR Gateway 2 Submission',
  siteAddress: 'TBC',
  clientName: 'TBC',
  applicationReference: 'TBC',
  reviewDate: new Date().toISOString(),
  gatewayStage: 'Gateway 2',
  documentVersion: '1.0'
};

/**
 * Generate formatted metadata display text
 */
export function formatProjectMetadata(metadata: ProjectMetadata): {
  title: string;
  subtitle: string;
  details: string[];
} {
  const reviewDate = new Date(metadata.reviewDate).toLocaleDateString('en-GB', {
    day: 'numeric',
    month: 'long',
    year: 'numeric'
  });

  return {
    title: metadata.projectName,
    subtitle: metadata.gatewayStage,
    details: [
      metadata.siteAddress ? `Site: ${metadata.siteAddress}` : '',
      metadata.clientName ? `Client: ${metadata.clientName}` : '',
      metadata.applicationReference ? `Ref: ${metadata.applicationReference}` : '',
      `Review Date: ${reviewDate}`,
      `Version: ${metadata.documentVersion || '1.0'}`,
      `Attlee AI v${BRAND_VERSION.version}`
    ].filter(Boolean)
  };
}

/**
 * CSS for PDF styling
 */
export function getPDFStyles(): string {
  return `
    * { margin: 0; padding: 0; box-sizing: border-box; }

    body {
      font-family: ${BRAND_TYPOGRAPHY.fontFamily.primary};
      font-size: ${BRAND_TYPOGRAPHY.fontSize.body};
      line-height: 1.6;
      color: ${BRAND_COLORS.textPrimary};
      padding: ${BRAND_LAYOUT.pdf.margin.top} ${BRAND_LAYOUT.pdf.margin.right} ${BRAND_LAYOUT.pdf.margin.bottom} ${BRAND_LAYOUT.pdf.margin.left};
      max-width: ${BRAND_LAYOUT.pdf.maxWidth};
      margin: 0 auto;
    }

    .cover-page {
      display: flex;
      flex-direction: column;
      justify-content: center;
      align-items: center;
      min-height: 100vh;
      text-align: center;
      page-break-after: always;
    }

    .cover-logo {
      font-size: ${BRAND_TYPOGRAPHY.fontSize.coverTitle};
      font-weight: ${BRAND_TYPOGRAPHY.fontWeight.bold};
      color: ${BRAND_COLORS.primary};
      margin-bottom: 20px;
    }

    .cover-title {
      font-size: 24pt;
      font-weight: ${BRAND_TYPOGRAPHY.fontWeight.semibold};
      color: ${BRAND_COLORS.textPrimary};
      margin-bottom: 40px;
    }

    .cover-subtitle {
      font-size: ${BRAND_TYPOGRAPHY.fontSize.h2};
      color: ${BRAND_COLORS.accent};
      margin-bottom: 60px;
    }

    .cover-metadata {
      font-size: ${BRAND_TYPOGRAPHY.fontSize.body};
      color: ${BRAND_COLORS.textSecondary};
      line-height: 2;
    }

    .header {
      border-bottom: 3px solid ${BRAND_COLORS.primary};
      padding-bottom: 20px;
      margin-bottom: 30px;
    }

    .header h1 {
      font-size: ${BRAND_TYPOGRAPHY.fontSize.h1};
      font-weight: ${BRAND_TYPOGRAPHY.fontWeight.semibold};
      color: ${BRAND_COLORS.primary};
      margin-bottom: 8px;
    }

    .header .meta {
      font-size: ${BRAND_TYPOGRAPHY.fontSize.small};
      color: ${BRAND_COLORS.textSecondary};
    }

    h2 {
      font-size: ${BRAND_TYPOGRAPHY.fontSize.h2};
      font-weight: ${BRAND_TYPOGRAPHY.fontWeight.semibold};
      color: ${BRAND_COLORS.primary};
      margin: 30px 0 16px 0;
      padding-bottom: 8px;
      border-bottom: 2px solid ${BRAND_COLORS.border};
      page-break-after: avoid;
    }

    h3 {
      font-size: ${BRAND_TYPOGRAPHY.fontSize.h3};
      font-weight: ${BRAND_TYPOGRAPHY.fontWeight.semibold};
      color: ${BRAND_COLORS.primary};
      margin: 24px 0 12px 0;
      page-break-after: avoid;
    }

    h4 {
      font-size: ${BRAND_TYPOGRAPHY.fontSize.h4};
      font-weight: ${BRAND_TYPOGRAPHY.fontWeight.semibold};
      color: ${BRAND_COLORS.textPrimary};
      margin: 20px 0 12px 0;
      page-break-after: avoid;
    }

    .footer {
      margin-top: 60px;
      padding-top: 20px;
      border-top: 2px solid ${BRAND_COLORS.border};
      font-size: ${BRAND_TYPOGRAPHY.fontSize.small};
      color: ${BRAND_COLORS.textSecondary};
      text-align: center;
    }

    @media print {
      body { padding: 20px 40px; }
      @page { margin: 1.5cm; }
    }
  `;
}
