"""
tests/fixtures/ground_truth.py — auto-generated by generate_test_pack.py
DO NOT EDIT MANUALLY.

Expected analysis results for the synthetic test pack.
All layer tests import GROUND_TRUTH and assert against its values.
"""

GROUND_TRUTH = {
    "total_documents": 21,
    "parts_covered": ["A", "B", "C"],

    # ── Coordination conflicts ────────────────────────────────────────────────
    # Both embedded at exact page/section in the named documents.
    "coordination_conflicts": [
        {
            "id": "CONFLICT-001",
            "type": "NUMERICAL",
            "part": "A",
            "pattern": "cladding_load",
            "doc_a": {
                "ref": "2.1.1", "page": 7,
                "section": "4.2 Façade Loading",
                "value": 2.5, "unit": "kN/m2"
            },
            "doc_b": {
                "ref": "2.3.3", "page": 4,
                "section": "3.1 System Self-Weight",
                "value": 1.8, "unit": "kN/m2"
            },
            "expected_severity": "HIGH",
        },
        {
            "id": "CONFLICT-002",
            "type": "NUMERICAL",
            "part": "B",
            "pattern": "sprinkler_activation_temperature",
            "doc_a": {
                "ref": "2.2.1", "page": 12,
                "section": "6.3 Sprinkler System",
                "value": 68, "unit": "°C"
            },
            "doc_b": {
                "ref": "2.2.3", "page": 3,
                "section": "2.1 Head Specification",
                "value": 93, "unit": "°C"
            },
            "expected_severity": "HIGH",
        },
    ],

    # ── Completeness gaps ─────────────────────────────────────────────────────
    # Topics absent from ALL documents in the relevant folder.
    # GAP-001: "disproportionate collapse" / "robustness strategy" / "key element"
    #          are absent from every Part_A_Structure document.
    # GAP-002: "cavity barrier" with positional reference (grid / level / elevation)
    #          is absent from every Part_B_Fire_Safety document.
    #          The phrase "cavity barrier" appears generically in 2.2.1 p.4 only.
    "completeness_gaps": [
        {
            "id": "GAP-001",
            "part": "A",
            "catalogue_id": "A-11",
            "missing_topic": "Strategy for robustness and disproportionate collapse",
            "absent_phrases": [
                "disproportionate collapse",
                "robustness strategy",
                "key element",
            ],
            "expected_severity": "HIGH",
        },
        {
            "id": "GAP-002",
            "part": "B",
            "catalogue_id": "B-07",
            "missing_topic": "Cavity barrier positions shown on elevations with grid references",
            "absent_pattern": "cavity barrier.*(?:grid|level|elevation|shown on|position)",
            "expected_severity": "HIGH",
        },
    ],

    # ── Expected scorecard spot-checks ────────────────────────────────────────
    # Keys are REJECTION_CATALOGUE ids from rejection_scorecard.py.
    # Values are the expected status when the scorecard is run against this pack.
    "expected_scorecard": {
        "A-11": "FAIL",   # Strategy for robustness and disproportionate collapse — GAP-001
        "A-17": "FAIL",   # Co-ordination mismatch — CONFLICT-001 (cladding load)
        "B-07": "FAIL",   # Cavity barrier positions — GAP-002
        "B-09": "FAIL",   # Sprinkler system layout — CONFLICT-002 keyword match
        "B-01": "PASS",   # Fire detection systems — present in Fire Strategy Report
    },

    # ── Folder → part mapping (for classifier accuracy tests) ─────────────────
    "folder_part_map": {
        "General_Application_Information": "ADMIN",
        "Part_A_Structure":               "A",
        "Part_B_Fire_Safety":             "B",
        "Part_C_Site_Preparation":        "C",
        "Mandatory_Documents":            "ADMIN",
    },

    # ── Document manifest ─────────────────────────────────────────────────────
    "documents": [
        {"ref": '0.1', "title": 'Application Information Schedule', "folder": 'General_Application_Information', "part": 'ADMIN', "filename": '0.1_Application_Information_Schedule_RevA.pdf'},
        {"ref": '0.2', "title": 'Application Project Brief', "folder": 'General_Application_Information', "part": 'ADMIN', "filename": '0.2_Application_Project_Brief_RevA.pdf'},
        {"ref": '0.3', "title": 'Application Folder Structure and Contents Schedule', "folder": 'General_Application_Information', "part": 'ADMIN', "filename": '0.3_Application_Folder_Structure_and_Contents_Schedule_RevA.pdf'},
        {"ref": '2.1.1', "title": 'Structural Calculation Pack', "folder": 'Part_A_Structure', "part": 'A', "filename": '2.1.1_Structural_Calculation_Pack_RevA.pdf'},
        {"ref": '2.1.2', "title": 'Structural General Arrangement Drawings', "folder": 'Part_A_Structure', "part": 'A', "filename": '2.1.2_Structural_General_Arrangement_Drawings_RevA.pdf'},
        {"ref": '2.1.3', "title": 'Geotechnical Ground Investigation Report', "folder": 'Part_A_Structure', "part": 'A', "filename": '2.1.3_Geotechnical_Ground_Investigation_Report_RevA.pdf'},
        {"ref": '2.1.4', "title": 'Pile Design and Testing Strategy', "folder": 'Part_A_Structure', "part": 'A', "filename": '2.1.4_Pile_Design_and_Testing_Strategy_RevA.pdf'},
        {"ref": '2.1.5', "title": 'Material Specification — Concrete and Steel', "folder": 'Part_A_Structure', "part": 'A', "filename": '2.1.5_Material_Specification_Concrete_and_Steel_RevA.pdf'},
        {"ref": '2.1.6', "title": 'Transfer Slab Design Note', "folder": 'Part_A_Structure', "part": 'A', "filename": '2.1.6_Transfer_Slab_Design_Note_RevA.pdf'},
        {"ref": '2.2.1', "title": 'Fire Strategy Report', "folder": 'Part_B_Fire_Safety', "part": 'B', "filename": '2.2.1_Fire_Strategy_Report_RevA.pdf'},
        {"ref": '2.2.2', "title": 'Fire Compartmentation Drawings', "folder": 'Part_B_Fire_Safety', "part": 'B', "filename": '2.2.2_Fire_Compartmentation_Drawings_RevA.pdf'},
        {"ref": '2.2.3', "title": 'MEP Sprinkler Design Specification', "folder": 'Part_B_Fire_Safety', "part": 'B', "filename": '2.2.3_MEP_Sprinkler_Design_Specification_RevA.pdf'},
        {"ref": '2.2.4', "title": 'Smoke Extraction Strategy Note', "folder": 'Part_B_Fire_Safety', "part": 'B', "filename": '2.2.4_Smoke_Extraction_Strategy_Note_RevA.pdf'},
        {"ref": '2.2.5', "title": 'Fire Door Schedule', "folder": 'Part_B_Fire_Safety', "part": 'B', "filename": '2.2.5_Fire_Door_Schedule_RevA.pdf'},
        {"ref": '2.2.6', "title": 'External Wall Fire Performance Assessment', "folder": 'Part_B_Fire_Safety', "part": 'B', "filename": '2.2.6_External_Wall_Fire_Performance_Assessment_RevA.pdf'},
        {"ref": '2.3.1', "title": 'Rainscreen Cladding Specification', "folder": 'Part_C_Site_Preparation', "part": 'C', "filename": '2.3.1_Rainscreen_Cladding_Specification_RevA.pdf'},
        {"ref": '2.3.2', "title": 'Below Ground Waterproofing Strategy', "folder": 'Part_C_Site_Preparation', "part": 'C', "filename": '2.3.2_Below_Ground_Waterproofing_Strategy_RevA.pdf'},
        {"ref": '2.3.3', "title": 'Facade Interface and Support Design', "folder": 'Part_C_Site_Preparation', "part": 'C', "filename": '2.3.3_Facade_Interface_and_Support_Design_RevA.pdf'},
        {"ref": '1.1', "title": 'Construction Control Plan', "folder": 'Mandatory_Documents', "part": 'ADMIN', "filename": '1.1_Construction_Control_Plan_RevA.pdf'},
        {"ref": '1.2', "title": 'Building Regulations Compliance Statement', "folder": 'Mandatory_Documents', "part": 'ADMIN', "filename": '1.2_Building_Regulations_Compliance_Statement_RevA.pdf'},
        {"ref": '1.3', "title": 'MOR Plan', "folder": 'Mandatory_Documents', "part": 'ADMIN', "filename": '1.3_MOR_Plan_RevA.pdf'},
    ],
}

# Convenience accessors
CONFLICTS   = GROUND_TRUTH["coordination_conflicts"]
GAPS        = GROUND_TRUTH["completeness_gaps"]
SCORECARD   = GROUND_TRUTH["expected_scorecard"]
