/**
 * Excel Export Service for Compliance Matrices
 *
 * Generates professional Excel spreadsheets with:
 * - Color-coded compliance status
 * - Auto-sized columns
 * - Frozen headers
 * - Filters
 *
 * UPDATED (GitHub Issues #7, #8, #9):
 * - #7: Consistent branding (colors, fonts)
 * - #8: Project metadata header (rows 1-13)
 * - #9: Resolution tracking columns (Status, Resolved By, Resolved Date)
 */

import ExcelJS from 'exceljs';
import type { ComplianceMatrix, ComplianceMatrixRow } from './compliance-matrix.js';
import {
  BRAND_COLORS,
  BRAND_LAYOUT,
  BRAND_LOGO,
  BRAND_VERSION,
  type ProjectMetadata,
  formatProjectMetadata
} from '../config/branding.js';

/**
 * Generate Excel workbook from compliance matrix
 */
export async function generateComplianceMatrixExcel(
  matrix: ComplianceMatrix,
  projectMetadata?: ProjectMetadata
): Promise<Buffer> {
  const workbook = new ExcelJS.Workbook();

  // Set workbook properties
  workbook.creator = BRAND_LOGO.text;
  workbook.created = new Date();
  workbook.modified = new Date();

  // Create main worksheet
  const worksheet = workbook.addWorksheet('Compliance Matrix', {
    views: [{ state: 'frozen', xSplit: 0, ySplit: BRAND_LAYOUT.excel.headerRow }] // Freeze header row
  });

  // Add project metadata header (GitHub Issue #8)
  if (projectMetadata) {
    addProjectMetadataHeader(worksheet, projectMetadata);
  }

  // Add title and summary
  addSummarySection(worksheet, matrix, projectMetadata ? 14 : 1);

  // Add data table (GitHub Issue #9: includes resolution tracking columns)
  addDataTable(worksheet, matrix);

  // Set print layout (landscape, fit to 1 page wide)
  worksheet.pageSetup = {
    paperSize: 9, // A4
    orientation: 'landscape',
    fitToPage: true,
    fitToWidth: 1,
    fitToHeight: 0, // Auto height
    margins: {
      left: 0.5,
      right: 0.5,
      top: 0.75,
      bottom: 0.75,
      header: 0.3,
      footer: 0.3
    },
    printTitlesRow: '14:14' // Repeat header row on each page
  };

  // Generate buffer
  const buffer = await workbook.xlsx.writeBuffer();
  return Buffer.from(buffer);
}

/**
 * Add project metadata header (GitHub Issue #8)
 */
function addProjectMetadataHeader(worksheet: ExcelJS.Worksheet, metadata: ProjectMetadata) {
  const formatted = formatProjectMetadata(metadata);

  // Row 1: Logo/Brand
  worksheet.addRow([BRAND_LOGO.text]);
  worksheet.getRow(1).font = { size: 18, bold: true, color: { argb: BRAND_COLORS.excel.primary } };
  worksheet.getRow(1).alignment = { vertical: 'middle', horizontal: 'left' };

  // Row 2: Project title
  worksheet.addRow(['Project:', formatted.title]);
  worksheet.getRow(2).font = { size: 12, bold: true };
  worksheet.getRow(2).getCell(2).font = { size: 12, bold: false };

  // Row 3: Gateway stage
  worksheet.addRow(['Gateway Stage:', formatted.subtitle]);
  worksheet.getRow(3).getCell(2).font = { color: { argb: BRAND_COLORS.excel.accent } };

  // Row 4-8: Metadata details
  let row = 4;
  for (const detail of formatted.details) {
    if (detail) {
      const [key, value] = detail.split(': ');
      worksheet.addRow([key + ':', value]);
      worksheet.getRow(row).getCell(1).font = { bold: true };
      row++;
    }
  }

  // Row 9-10: Blank separator
  worksheet.addRow([]);
  worksheet.addRow([]);

  // Row 11-13: Instructions
  worksheet.addRow(['COMPLIANCE MATRIX']);
  worksheet.getRow(11).font = { size: 14, bold: true, color: { argb: BRAND_COLORS.excel.primary } };

  worksheet.addRow(['This matrix tracks all regulatory requirements and their compliance status.']);
  worksheet.getRow(12).font = { size: 10, italic: true, color: { argb: 'FF64748B' } };

  worksheet.addRow(['Use the Resolution Status column to track remediation progress.']);
  worksheet.getRow(13).font = { size: 10, italic: true, color: { argb: 'FF64748B' } };
}

/**
 * Add summary section (fallback when no project metadata)
 */
function addSummarySection(worksheet: ExcelJS.Worksheet, matrix: ComplianceMatrix, startRow: number = 1) {
  // Skip if not used (when projectMetadata is provided, this is not called)
  if (startRow !== 1) return;

  // Title
  worksheet.addRow([BRAND_LOGO.text.toUpperCase()]);
  worksheet.getRow(1).font = { size: 16, bold: true, color: { argb: BRAND_COLORS.excel.primary } };
  worksheet.getRow(1).alignment = { vertical: 'middle', horizontal: 'left' };

  // Project info
  worksheet.addRow(['Project:', matrix.projectName]);
  worksheet.addRow(['Generated:', new Date(matrix.generatedDate).toLocaleDateString('en-GB')]);
  worksheet.addRow(['Generated by:', BRAND_LOGO.footer]);
  worksheet.getRow(4).font = { italic: true, color: { argb: 'FF64748B' } };
  worksheet.addRow([]); // Blank row

  // Summary stats
  worksheet.addRow(['SUMMARY']);
  worksheet.getRow(6).font = { size: 12, bold: true, color: { argb: BRAND_COLORS.excel.primary } };

  worksheet.addRow(['Total Requirements:', matrix.totalRequirements]);
  worksheet.addRow(['Met:', matrix.met, `${Math.round((matrix.met / matrix.totalRequirements) * 100)}%`]);
  worksheet.addRow(['Partial:', matrix.partial, `${Math.round((matrix.partial / matrix.totalRequirements) * 100)}%`]);
  worksheet.addRow(['Not Met:', matrix.notMet, `${Math.round((matrix.notMet / matrix.totalRequirements) * 100)}%`]);
  worksheet.addRow(['Compliance Rate:', `${matrix.complianceRate}%`]);

  // Color code summary (using brand colors)
  worksheet.getRow(8).getCell(3).fill = {
    type: 'pattern',
    pattern: 'solid',
    fgColor: { argb: BRAND_COLORS.excel.success }
  };
  worksheet.getRow(9).getCell(3).fill = {
    type: 'pattern',
    pattern: 'solid',
    fgColor: { argb: BRAND_COLORS.excel.warning }
  };
  worksheet.getRow(10).getCell(3).fill = {
    type: 'pattern',
    pattern: 'solid',
    fgColor: { argb: BRAND_COLORS.excel.danger }
  };

  worksheet.addRow([]); // Blank row
  worksheet.addRow([]); // Blank row
}

/**
 * Add main data table
 */
function addDataTable(worksheet: ExcelJS.Worksheet, matrix: ComplianceMatrix) {
  const startRow = BRAND_LAYOUT.excel.headerRow;

  // Define columns (GitHub Issue #9: added resolution tracking)
  const columns = [
    { header: 'ID', key: 'id', width: BRAND_LAYOUT.excel.columnWidths.id },
    { header: 'Requirement', key: 'requirement', width: BRAND_LAYOUT.excel.columnWidths.requirement },
    { header: 'Category', key: 'category', width: BRAND_LAYOUT.excel.columnWidths.category },
    { header: 'Status', key: 'status', width: BRAND_LAYOUT.excel.columnWidths.status },
    { header: 'Priority', key: 'priority', width: BRAND_LAYOUT.excel.columnWidths.priority },
    { header: "What's Wrong", key: 'whatsWrong', width: BRAND_LAYOUT.excel.columnWidths.whatsWrong },
    { header: 'Why It Matters', key: 'whyItMatters', width: BRAND_LAYOUT.excel.columnWidths.whyItMatters },
    { header: 'Request', key: 'request', width: BRAND_LAYOUT.excel.columnWidths.request },
    { header: 'Owner', key: 'owner', width: BRAND_LAYOUT.excel.columnWidths.owner },
    { header: 'Evidence Document', key: 'evidenceDoc', width: BRAND_LAYOUT.excel.columnWidths.evidenceDoc },
    { header: 'Page', key: 'page', width: BRAND_LAYOUT.excel.columnWidths.page },
    { header: 'Evidence Quote', key: 'evidenceQuote', width: BRAND_LAYOUT.excel.columnWidths.evidenceQuote },
    { header: 'Evidence Quality', key: 'evidenceQuality', width: BRAND_LAYOUT.excel.columnWidths.evidenceQuality },
    { header: 'Notes', key: 'notes', width: BRAND_LAYOUT.excel.columnWidths.notes },
    // Resolution tracking columns (GitHub Issue #9)
    { header: 'Resolution Status', key: 'resolutionStatus', width: BRAND_LAYOUT.excel.columnWidths.resolutionStatus },
    { header: 'Resolved By', key: 'resolvedBy', width: BRAND_LAYOUT.excel.columnWidths.resolvedBy },
    { header: 'Resolved Date', key: 'resolvedDate', width: BRAND_LAYOUT.excel.columnWidths.resolvedDate }
  ];

  worksheet.columns = columns;

  // Style header row (GitHub Issue #7: brand colors)
  const headerRow = worksheet.getRow(startRow);
  headerRow.values = columns.map(c => c.header);
  headerRow.font = { bold: true, color: { argb: BRAND_COLORS.excel.headerText } };
  headerRow.fill = {
    type: 'pattern',
    pattern: 'solid',
    fgColor: { argb: BRAND_COLORS.excel.primary }
  };
  headerRow.alignment = { vertical: 'middle', horizontal: 'center' };
  headerRow.height = 20;

  // Add data rows (GitHub Issue #9: includes resolution tracking)
  matrix.rows.forEach((row, index) => {
    // Determine default resolution status based on compliance status
    const defaultResolutionStatus = row.status === 'Met' ? 'N/A' : 'Open';

    const excelRow = worksheet.addRow({
      id: row.requirementId,
      requirement: row.requirement,
      category: row.category,
      status: row.status,
      priority: row.priority || '',
      whatsWrong: row.whatsWrong || '',
      whyItMatters: row.whyItMatters || '',
      request: row.request || '',
      owner: row.owner || '',
      evidenceDoc: row.evidenceDocument || 'Not provided',
      page: row.evidencePage || '',
      evidenceQuote: truncate(row.evidenceQuote || '', 200),
      evidenceQuality: row.evidenceQuality || '',
      notes: truncate(row.notes || '', 200),
      // Resolution tracking (GitHub Issue #9)
      resolutionStatus: defaultResolutionStatus,
      resolvedBy: '',
      resolvedDate: ''
    });

    // Color code by status (new triage-based statuses)
    const statusCell = excelRow.getCell('status');
    switch (row.status) {
      case 'Met':
        statusCell.fill = {
          type: 'pattern',
          pattern: 'solid',
          fgColor: { argb: 'FFD4EDDA' } // Green
        };
        statusCell.font = { color: { argb: 'FF155724' }, bold: true };
        break;
      case 'Review Required':
        statusCell.fill = {
          type: 'pattern',
          pattern: 'solid',
          fgColor: { argb: 'FFFFF3CD' } // Yellow
        };
        statusCell.font = { color: { argb: 'FF856404' }, bold: true };
        break;
      case 'Blocker':
        statusCell.fill = {
          type: 'pattern',
          pattern: 'solid',
          fgColor: { argb: 'FFDC2626' } // Bright red
        };
        statusCell.font = { color: { argb: 'FFFFFFFF' }, bold: true };
        break;
      case 'Missing Info':
        statusCell.fill = {
          type: 'pattern',
          pattern: 'solid',
          fgColor: { argb: 'FFF8D7DA' } // Light red
        };
        statusCell.font = { color: { argb: 'FF721C24' }, bold: true };
        break;
    }

    // Color code by priority
    const priorityCell = excelRow.getCell('priority');
    if (row.priority === 'Critical') {
      priorityCell.font = { color: { argb: 'FFDC2626' }, bold: true };
    } else if (row.priority === 'High') {
      priorityCell.font = { color: { argb: 'FFF59E0B' }, bold: true };
    }

    // Color code resolution status (GitHub Issue #9)
    const resolutionCell = excelRow.getCell('resolutionStatus');
    const resolutionStatus = resolutionCell.value as string;
    switch (resolutionStatus) {
      case 'Open':
        resolutionCell.fill = {
          type: 'pattern',
          pattern: 'solid',
          fgColor: { argb: BRAND_COLORS.excel.statusOpen }
        };
        resolutionCell.font = { bold: true };
        break;
      case 'In Progress':
        resolutionCell.fill = {
          type: 'pattern',
          pattern: 'solid',
          fgColor: { argb: BRAND_COLORS.excel.statusInProgress }
        };
        resolutionCell.font = { bold: true };
        break;
      case 'Resolved':
        resolutionCell.fill = {
          type: 'pattern',
          pattern: 'solid',
          fgColor: { argb: BRAND_COLORS.excel.statusResolved }
        };
        resolutionCell.font = { color: { argb: 'FF155724' }, bold: true };
        break;
      case 'N/A':
      case 'Not Applicable':
        resolutionCell.fill = {
          type: 'pattern',
          pattern: 'solid',
          fgColor: { argb: BRAND_COLORS.excel.statusNA }
        };
        resolutionCell.font = { color: { argb: 'FF64748B' }, italic: true };
        break;
    }

    // Alternate row colors for readability
    if (index % 2 === 0) {
      excelRow.fill = {
        type: 'pattern',
        pattern: 'solid',
        fgColor: { argb: 'FFF8FAFC' } // Light gray
      };
    }

    // Text wrapping for long cells
    excelRow.getCell('requirement').alignment = { wrapText: true, vertical: 'top' };
    excelRow.getCell('whatsWrong').alignment = { wrapText: true, vertical: 'top' };
    excelRow.getCell('whyItMatters').alignment = { wrapText: true, vertical: 'top' };
    excelRow.getCell('request').alignment = { wrapText: true, vertical: 'top' };
    excelRow.getCell('evidenceQuote').alignment = { wrapText: true, vertical: 'top' };
    excelRow.getCell('notes').alignment = { wrapText: true, vertical: 'top' };
    excelRow.height = 30; // Taller rows for wrapped text
  });

  // Add autofilter
  worksheet.autoFilter = {
    from: { row: startRow, column: 1 },
    to: { row: startRow + matrix.rows.length, column: columns.length }
  };

  // Add borders to all data cells
  for (let i = startRow; i <= startRow + matrix.rows.length; i++) {
    const row = worksheet.getRow(i);
    for (let j = 1; j <= columns.length; j++) {
      const cell = row.getCell(j);
      cell.border = {
        top: { style: 'thin', color: { argb: 'FFE2E8F0' } },
        left: { style: 'thin', color: { argb: 'FFE2E8F0' } },
        bottom: { style: 'thin', color: { argb: 'FFE2E8F0' } },
        right: { style: 'thin', color: { argb: 'FFE2E8F0' } }
      };
    }
  }
}

/**
 * Truncate text to max length
 */
function truncate(text: string, maxLength: number): string {
  if (text.length <= maxLength) return text;
  return text.substring(0, maxLength - 3) + '...';
}
